### ISSUE TITLE
Do I add patrick to the Remotes field inside DESCRIPTION?

### ISSUE THREAD

**Issue by howardbaik** [google/patrick#15]
In the README, you suggest adding patrick to Suggests and Remotes within a package's DESCRIPTION. However, in the code chunk, you only add it to Suggests. 

I'm a bit confused as to why patrick should be added to Remotes. According to the R packages [book](https://r-pkgs.org/dependencies-in-practice.html#depending-on-the-development-version-of-a-package), _the Remotes field can be used when you need to install a dependency from a nonstandard place, i.e. from somewhere besides CRAN or Bioconductor._  

patrick seems to be in a standard place, i.e. CRAN

**Comment by michaelquinn32** [comment]
Hi Howard!

Sorry about that.

I missed something when doing this:
https://github.com/google/patrick/commit/54e0829f7c1f43acc0f49879ee517a60d966b765

You don't need to use `patrick` in `Remotes`. Adding it to `Suggests` is sufficient.

Best wishes,
Michael

**Comment by howardbaik** [comment]
No problem, and thanks for letting me know!
