### ISSUE TITLE
Supply a glue-formatted string to `.test_names=` for building the name from `.cases`

### ISSUE THREAD

**Issue by MichaelChirico** [google/patrick#18]
WDYT about an extension here where `.test_names=` can be a glue-formatted string?

```r
with_parameters_test_that("str", { ... },
  .test_names = "{x} case where {y}, {z}",
  x = ...
  y = ...
  z = ...
)
```

The actual test name is filled out with `x[i], y[i], z[i]`.

Not fully back-compatible in the case that (1) `.test_names` were previously supplied with `{` _and_ (2) the symbol inside `{...}` resolves to a variable in the parameters. But I don't think it'll break anything, just weird test names maybe, and seems rare anyway.

_Originally posted by @MichaelChirico in https://github.com/google/patrick/issues/11#issuecomment-1833039774_
            
Filing as an issue to make sure it's not lost in the PR comments.

**Comment by hadley** [comment]
IMO the test name should be glue interpolated by default so that:

```R

with_parameters_test_that("Data is successfully converted:", {
    input <- convert(test_data)
    expect_type(input, type)
  },
  test_data = list(numeric_data, character_data),
  type = c("double", "character"),
  .test_name = type
)
```

Becomes:

```R

with_parameters_test_that("{type} data is successfully converted", {
    input <- convert(test_data)
    expect_type(input, type)
  },
  test_data = list(numeric_data, character_data),
  type = c("double", "character")
)
```

**Comment by michaelquinn32** [comment]
Thanks for the suggestion. It should be easy enough to support both as glue-formatted strings.
