### ISSUE TITLE
Warning for code outside  `test_that()`

### ISSUE THREAD

**Issue by fritjoflammers** [google/patrick#7]
This is a great package and really worthwhile extension to testthat. It works great and is really intuitive to use!

One thing I noticed is that `test_that` throws the following warning and I just wanted to know if that's because of a mistake I made, or possibly a known issue.

**Code**
```
with_parameters_test_that(
  "distance_result_matches_test_data",
  {
    expect_equal(group_distance(m1,m2), result, tolerance=1e-6)
  },
  cases(
    case1 = list(m1=test_data$A1, m2=test_data$A2, result=test_data$result[1]),
    case2 = list(m1=test_data$B1, m2=test_data$B2, result=test_data$result[2]),
    case3 = list(m1=test_data$C1, m2=test_data$C2, result=test_data$result[3]),
    case4 = list(m1=test_data$D1, m2=test_data$D2, result=test_data$result[4]),
    case5 = list(m1=test_data$E1, m2=test_data$E2, result=test_data$result[5])
  )
)
```

**Warning**

```
── Warning (test_distance.R:19:1): (code run outside of `test_that()`) ─────────
The `code` argument to `test_that()` must be a braced expression to get accurate file-line information for failures.
Backtrace:
 1. patrick::with_parameters_test_that(...) test_distance.R:19:0
 2. purrr::pmap(all_pars, build_and_run_test, desc = desc_stub, code = captured)
 3. patrick:::.f(...)
 4. testthat::test_that(completed_desc, rlang::eval_tidy(code, args))
```

Thanks, 

Fritjof

**Comment by michaelquinn32** [comment]
Thanks for reporting this!

It seems clear that I need to do some updates to get patrick to work with testthat 3e. It should be OK to suppress those warnings, but I want to make sure that features like line references still make sense.

**Comment by michaelquinn32** [comment]
I'm putting together a release right now to address this issue. You can install the draft release with the following:

```
remotes::install_github("google/patrick")
```

I'll close this once the release is finished.

Thanks again for using patrick and reporting the issue!!

**Comment by michaelquinn32** [comment]
And we're up on CRAN. Thanks again!

**Comment by fritjoflammers** [comment]
Wow, thanks for the quick response! Works great :+1:
