### ISSUE TITLE
Support automatic test case naming

### ISSUE THREAD

**Issue by michaelquinn32** [google/patrick#8]
This deserves a bit of thought before going forward

*  right now the fallback is to have no name, which obviously isn't ideal
*  deparsing might be the right next step
*  i also need something like snapshot testing to actually look at the testcase output to be sure that it's sensible

**Comment by MichaelChirico** [comment]
`deparse()` comes with its own headaches (though I do think it's probably the right way to go) -- a minimal-overhead approach is to just use `seq_along` to number the tests. At least that way the test failures will have unique names.

**Comment by MichaelChirico** [comment]
I think a good use case to have in mind here is replacing a simple `for` loop with a patrick test.

With `for` loop:

```
for (name in names) {
  test_that(sprintf("works: %s", name), {
    # expectations depending on 'name'
  })
}
```

replaced with

```
with_parameters_test_that(
  "works:",
  {
    # expectations depending on 'name'
  },
  name = names
)
```

A big appeal of the `for` loop is that `names` can be a literal & we don't need to store any variables in the test env, nor to repeat ourselves by spelling out `names` >once.

Whereas the appeal of doing this through `patrick` is (1) API consistency within a test suite (2) makes it clearer the purpose is to do a templated series of tests (slightly less clear in `for` loop approach, especially with a bigger `{...}` body) and (3) obviates the distracting `sprintf()` test name construction part.

**Comment by MichaelChirico** [comment]
I think this is the same as a new issue I was about to post:

The more I use `patrick()` the more I find myself writing code like:

```
with_parameters_test_that(
  "a test name",
  { some_test_exprs(single_param) },
  .test_name = FOO,
  single_param = FOO
)
```

This feels pretty redundant. It seems like using `.test_name = params[[1]]` when `length(params) == 1` is a reasonable default.

Alternatively, accepting syntax like

`single_param = FOO, .test_name = single_param` (or even `"single_param"` to avoid NSE headaches)

would generalize to higher-cardinality tests where `.test_name` is still drawn directly from one of the test parameters
