### ISSUE TITLE
Creating factorial tests

### ISSUE THREAD

**Issue by MichaelChirico** [google/patrick#9]
I'd like to run some factorial tests where the parameters are `expand.grid(A, B)`. Is there an easier way to accomplish this in `patrick` than:

```
param_df <- expand.grid(A, B)
patrick::with_parameters_test_that(
  "factorial test",
  expect_passes(foo(A, B))
  .test_name = "test",
  A = param_df$A,
  B = param_df$B
)
```

If not, could we build this into the API? e.g. `.factorial = list(A, B)` auto-expands as `do.call(expand.grid, .factorial)` (perhaps with also setting `stringsAsFactors=FALSE`?)

**Comment by michaelquinn32** [comment]
You should be able to use `.cases` for this.

```
A <- rep(TRUE, 3)
B <- rep(TRUE, 2)

patrick::with_parameters_test_that(
  "factorial test",
  expect_equal(A, B),
  .cases = expand.grid(A = A, B = B) %>% tibble::rownames_to_column(".test_name")
)
```

The edge case above is that there isn't automatic test name generation. That's #8 again

**Comment by MichaelChirico** [comment]
I think what I'm after here is for `patrick()` to run the `expand.grid()` code for me under the hood. As we see in your example, it's somewhat clunky -- I'd like to hide the knotty bits inside `patrick()` to unclutter the test code.

**Comment by MichaelChirico** [comment]
I keep coming back to this, still no great insight on what to do.

I think my biggest issue with the `expand.grid()` approach is the need to specify `.test_name`.

WDYT about more generally in patrick auto-naming tests if not provided?

Something like `paste(A, B)` would be good enough, or even something like "A={A}, B={B}".

That would clean up the API a bit, WDYT?
